### ISSUE TITLE
adapt this script to call and output other files

### ISSUE THREAD

**Issue by TwinMist** [seanhuber/bootstrap-progress-modal#2]
Love the layout of this script and wondered it anyone help me to adapt this script to call and output other files
ie
step 1
  run file1.php and output response
step 2
  run file2.php and output response

thanks

**Comment by seanhuber** [comment]
Well this is a javascript/jquery utility (which runs client-side in the browser) so if you want to execute PHP files you'll need to make http requests (ajax) to run server-side php code.

Google for how to do ajax with jquery. There are a lot of good tutorials on the internet.

**Comment by TwinMist** [comment]
thanks, i am no coder and been trying for days to get something working. I love your design. do you have any spare time to help me out using your code?
many thanks
